FROM gradle:jdk11

WORKDIR /app

# Copy required project files
COPY build.gradle settings.gradle /app/
COPY src /app/src

# Build for production
RUN gradle --no-daemon build

# Start
CMD ["java","-jar","/app/build/libs/discovery-server-0.0.1-SNAPSHOT.jar"]
