spring:
  datasource:
    hikari:
      maximum-pool-size: 1
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: map-service
  config:
    import: optional:file:.env[.properties]
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${DOMAIN}

auth0:
  audience: ${AUDIENCE}

server:
  port: ${PORT:8080}
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true