FROM rust:latest as build

COPY . ./app

WORKDIR /app

RUN cargo build --release

FROM gcr.io/distroless/cc

COPY --from=build /app/target/release/notes-service /usr/local/bin/app
COPY --from=build /usr/lib/x86_64-linux-gnu/libpq.so.5 \
	/usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2 \
	/usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2 \
	/usr/lib/x86_64-linux-gnu/libkrb5.so.3 \
	/usr/lib/x86_64-linux-gnu/libk5crypto.so.3 \
	/usr/lib/x86_64-linux-gnu/libkrb5support.so.0 \
	/usr/lib/x86_64-linux-gnu/liblber-2.4.so.2 \
	/usr/lib/x86_64-linux-gnu/libsasl2.so.2 \
	/usr/lib/x86_64-linux-gnu/libgnutls.so.30 \
	/usr/lib/x86_64-linux-gnu/libp11-kit.so.0 \
	/usr/lib/x86_64-linux-gnu/libidn2.so.0 \
	/usr/lib/x86_64-linux-gnu/libunistring.so.2 \
	/usr/lib/x86_64-linux-gnu/libtasn1.so.6 \
	/usr/lib/x86_64-linux-gnu/libnettle.so.8 \
	/usr/lib/x86_64-linux-gnu/libhogweed.so.6 \
	/usr/lib/x86_64-linux-gnu/libgmp.so.10 \
	/usr/lib/x86_64-linux-gnu/libffi.so.7 \
	/lib/x86_64-linux-gnu/libcom_err.so.2 \
	/lib/x86_64-linux-gnu/libkeyutils.so.1 /lib/x86_64-linux-gnu/

ARG DATABASE_URL
ARG AUTHORITY
ARG PORT

ENV DATABASE_URL=$DATABASE_URL
ENV AUTHORITY=$AUTHORITY
ENV PORT=$PORT

ENTRYPOINT ["app"]