FROM gradle:jdk11

WORKDIR /app

# Copy required project files
COPY build.gradle settings.gradle /app/
COPY src /app/src

# Set enivornment variables
ARG DB_URL
ARG DB_USERNAME
ARG DB_PASSWORD

ENV DB_URL=$DB_URL
ENV DB_USERNAME=$DB_USERNAME
ENV DB_PASSWORD=$DB_PASSWORD

# Build for production
RUN gradle --no-daemon build

# Start
CMD ["java","-jar","/app/build/libs/map-service-0.0.1-SNAPSHOT.jar"]
