name: CI/CD

on:
  pull_request:
    branches: production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn --update-snapshots verify

    - name: Build Docker image
      run: docker build -t registry.heroku.com/${{ secrets.HEROKU_APP }}/web:latest 
            --build-arg DOMAIN=${{ secrets.INFO_MAP_AUTH0_DOMAIN }}
            --build-arg AUDIENCE=${{ secrets.INFO_MAP_AUTH0_AUDIENCE }} 
            --build-arg DB_URL=${{ secrets.DB_URL }} 
            --build-arg DB_USERNAME=${{ secrets.DB_USERNAME }} 
            --build-arg DB_PASSWORD=${{ secrets.DB_PASSWORD }} .

    - name: Docker image info
      run: docker images

    - name: Login to container registry
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:login

    - name: Push Docker image
      run: docker push registry.heroku.com/${{ secrets.HEROKU_APP }}/web

    - name: Release
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:release -a ${{ secrets.HEROKU_APP }} web