name: notes-service CI/CD

on:
  pull_request:
    branches: production
    paths:
      - 'notes-service/**'
defaults: 
  run: 
    working-directory: notes-service

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Update local toolchain
      run: |
        rustup update
        rustup install nightly

    - name: Toolchain info
      run: |
        cargo --version
        rustc --version

    # - name: Test
    #   run: |
    #     cargo test --workspace

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
    - name: Build Docker image
      run: docker build -t registry.heroku.com/${{ secrets.NOTES_SERVICES_HEROKU_APP }}/web:latest 
            --build-arg DATABASE_URL=${{ secrets.NOTES_SERVICES_DATABASE_URL }}
            --build-arg AUTHORITY=${{ secrets.INFO_MAP_AUTH0_DOMAIN }} .

    - name: Docker image info
      run: docker images

    - name: Login to container registry
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:login

    - name: Push Docker image
      run: docker push registry.heroku.com/${{ secrets.NOTES_SERVICES_HEROKU_APP }}/web

    - name: Release
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:release -a ${{ secrets.NOTES_SERVICES_HEROKU_APP }} web